version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free:23.3
    container_name: oracle-db
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: admin250420
      ORACLE_DATABASE: orcl
      APP_USER: admin
      APP_USER_PASSWORD: admin250420
    ports:
      - "1521:1521"
    networks:
      - ords_net

  ords:
    build: .
    container_name: ords-test
    restart: unless-stopped
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    networks:
      - ords_net

networks:
  ords_net:
    driver: bridge
