#!/bin/bash

echo "📥 ORDS Download Helper"
echo "======================="
echo ""
echo "To get the real ORDS UI, you need to:"
echo ""
echo "1. 📋 Go to Oracle's ORDS download page:"
echo "   https://www.oracle.com/database/technologies/appdev/rest-data-services-downloads.html"
echo ""
echo "2. 📥 Download ORDS (you'll need an Oracle account)"
echo "   - Look for 'Oracle REST Data Services'"
echo "   - Download the ZIP file"
echo ""
echo "3. 📦 Extract the ZIP file and find ords.war"
echo "   - Extract the downloaded ZIP"
echo "   - Look for ords.war in the extracted files"
echo ""
echo "4. 📁 Place ords.war in this directory"
echo "   - Copy ords.war to: $(pwd)/ords.war"
echo ""
echo "5. 🔨 Rebuild the container:"
echo "   docker-compose build --no-cache"
echo "   docker-compose up -d"
echo ""
echo "6. 🌐 Access the real ORDS UI:"
echo "   http://localhost:8080/ords/"
echo ""
echo "💡 Note: You need an Oracle account to download ORDS"
echo "   If you don't have one, you can create a free account at:"
echo "   https://profile.oracle.com/myprofile/account/create-account.jspx"
echo ""
